server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on; gzip_types application/json application/javascript text/css;
    location /data/ { add_header Cache-Control "no-cache"; }
    location ~* \.(js|css)$ { add_header Cache-Control "public, max-age=3600"; }
    location / { try_files $uri $uri/ /index.html; }
}
